
spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/cms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=cmsuser
spring.datasource.password=cmspass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb://localhost:27017/cms
api.path=/
secret=01234567890123456789012345678901
